export default {
  ADD_CONNECTION: 'ADD_CONNECTION',
  ADD_CONNECTION_FOR_SENSOR: 'ADD_CONNECTION_FOR_SENSOR',
  ADD_HTMLIDMAPPING: 'ADD_HTMLIDMAPPING',
  ADD_NODE: 'ADD_NODE',
  ADD_SENSOR: 'ADD_SENSOR',

  FETCH_NODE_IDS_HAS_ERRORED: 'FETCH_NODE_IDS_HAS_ERRORED',
  FETCH_NODE_IDS_IS_LOADING: 'FETCH_NODE_IDS_IS_LOADING',
  FETCH_NODE_IDS_SUCCESS: 'FETCH_NODE_IDS_SUCCESS',

  FETCH_NODE_HAS_ERRORED: 'FETCH_NODE_HAS_ERRORED',
  FETCH_NODE_IS_LOADING: 'FETCH_NODE_IS_LOADING',
  FETCH_NODE_SUCCESS: 'FETCH_NODE_SUCCESS',

  FETCH_SENSOR_HAS_ERRORED: 'FETCH_SENSOR_HAS_ERRORED',
  FETCH_SENSOR_IS_LOADING: 'FETCH_SENSOR_IS_LOADING',
  FETCH_SENSOR_SUCCESS: 'FETCH_SENSOR_SUCCESS',

  MOVE_NODE: 'MOVE_NODE',
  MOVE_SENSOR: 'MOVE_SENSOR',

  REMOVE_NODE: 'REMOVE_NODE',
  REMOVE_SENSOR: 'REMOVE_SENSOR',

  UPDATE_CONNECTION: 'UPDATE_CONNECTION',
  UPDATE_HTMLIDMAPPING: 'UPDATE_HTMLIDMAPPING',
  UPDATE_SENSOR_VALUE: 'UPDATE_SENSOR_VALUE'
};
