export const Actions = {
  ADD_NODE: 'ADD_NODE',
  ADD_SENSOR: 'ADD_SENSOR',
  FETCH_NODE_IDS_HAS_ERRORED: 'FETCH_NODE_IDS_HAS_ERRORED',
  FETCH_NODE_IDS_IS_LOADING: 'FETCH_NODE_IDS_IS_LOADING',
  FETCH_NODE_IDS_SUCCESS: 'FETCH_NODE_IDS_SUCCESS',
  FETCH_NODE_HAS_ERRORED: 'FETCH_NODE_HAS_ERRORED',
  FETCH_NODE_IS_LOADING: 'FETCH_NODE_IS_LOADING',
  FETCH_NODE_SUCCESS: 'FETCH_NODE_SUCCESS'
};
