export default {
  ADD_CONNECTION: 'ADD_CONNECTION',
  ADD_CONNECTION_FOR_SENSOR: 'ADD_CONNECTION_FOR_SENSOR',
  ADD_HTMLIDMAPPING: 'ADD_HTMLIDMAPPING',
  ADD_MAPPING: 'ADD_MAPPING',
  ADD_SENSOR: 'ADD_SENSOR',
  BUILD_REQUEST: 'BUILD_REQUEST',
  CREATE_NEW_MAPPING: 'CREATE_NEW_MAPPING',
  CLEAR_MAPPING_DIALOG: 'CLEAR_MAPPING_DIALOG',
  CLOSE_MAPPING_DIALOG: 'CLOSE_MAPPING_DIALOG',
  CLOSE_MENU_DRAWER: 'CLOSE_MENU_DRAWER',

  FETCH_SENSOR_HAS_ERRORED: 'FETCH_SENSOR_HAS_ERRORED',
  FETCH_SENSOR_IS_LOADING: 'FETCH_SENSOR_IS_LOADING',
  FETCH_SENSOR_SUCCESS: 'FETCH_SENSOR_SUCCESS',

  FETCH_MAPPING_HAS_ERRORED: 'FETCH_SENSOR_HAS_ERRORED',
  FETCH_MAPPING_IS_LOADING: 'FETCH_SENSOR_IS_LOADING',
  FETCH_MAPPING_SUCCESS: 'FETCH_SENSOR_SUCCESS',

  HANDLE_REQUEST_RESPONSE: 'HANDLE_REQUEST_RESPONSE',
  HIDE_MODAL: 'HIDE_MODAL',

  MOVE_CHART: 'MOVE_CHART',
  MOVE_SENSOR: 'MOVE_SENSOR',

  OPEN_MAPPING_DIALOG: 'OPEN_MAPPING_DIALOG',
  OPEN_MENU_DRAWER: 'OPEN_MENU_DRAWER',

  PIN_CHART: 'PIN_CHART',
  REMOVE_CONNECTION: 'REMOVE_CONNECTION',
  REMOVE_MAPPING: 'REMOVE_MAPPING',
  REMOVE_SENSOR: 'REMOVE_SENSOR',

  SAVE_MAPPING: 'SAVE_MAPPING',
  SEND_REQUEST: 'SEND_REQUEST',
  SET_MAPPING_ACTIVE: 'SET_MAPPING_ACTIVE',
  SET_MAPPING_INACTIVE: 'SET_MAPPING_INACTIVE',
  SHOW_MODAL: 'SHOW_MODAL',

  UNPIN_CHART: 'UNPIN_CHART',
  UPDATE_CONNECTION: 'UPDATE_CONNECTION',
  UPDATE_HTMLIDMAPPING: 'UPDATE_HTMLIDMAPPING',
  UPDATE_MAPPING_DIALOG: 'UPDATE_MAPPING_DIALOG',
  UPDATE_MAPPING_VALUE: 'UPDATE_MAPPING_VALUE',
  UPDATE_SENSOR_VALUE: 'UPDATE_SENSOR_VALUE'
};
