export default {
  ADD_CONNECTION: 'ADD_CONNECTION',
  ADD_CONNECTION_FOR_SENSOR: 'ADD_CONNECTION_FOR_SENSOR',
  ADD_HTMLIDMAPPING: 'ADD_HTMLIDMAPPING',
  ADD_MAPPING: 'ADD_MAPPING',
  ADD_SENSOR: 'ADD_SENSOR',
  ADD_SENSOR_TO_NODE: 'ADD_SENSOR_TO_NODE',
  CLEAR_MAPPING_DIALOG: 'CLEAR_MAPPING_DIALOG',
  CLOSE_MAPPING_DIALOG: 'CLOSE_MAPPING_DIALOG',

  FETCH_SENSOR_HAS_ERRORED: 'FETCH_SENSOR_HAS_ERRORED',
  FETCH_SENSOR_IS_LOADING: 'FETCH_SENSOR_IS_LOADING',
  FETCH_SENSOR_SUCCESS: 'FETCH_SENSOR_SUCCESS',

  HANDLE_REQUEST_RESPONSE: 'HANDLE_REQUEST_RESPONSE',
  HIDE_MODAL: 'HIDE_MODAL',

  MOVE_SENSOR: 'MOVE_SENSOR',

  OPEN_MAPPING_DIALOG: 'OPEN_MAPPING_DIALOG',

  REMOVE_CONNECTION: 'REMOVE_CONNECTION',
  REMOVE_MAPPING: 'REMOVE_MAPPING',
  REMOVE_SENSOR: 'REMOVE_SENSOR',

  SAVE_MAPPING: 'SAVE_MAPPING',
  SEND_REQUEST: 'SEND_REQUEST',
  SHOW_MODAL: 'SHOW_MODAL',

  UPDATE_CONNECTION: 'UPDATE_CONNECTION',
  UPDATE_HTMLIDMAPPING: 'UPDATE_HTMLIDMAPPING',
  UPDATE_MAPPING_DIALOG: 'UPDATE_MAPPING_DIALOG',
  UPDATE_SENSOR_VALUE: 'UPDATE_SENSOR_VALUE'
};
